application:
  rabbit:
    enable: true
logging:
  level:
    ru.digitalleague.core: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 135246
    url: jdbc:postgresql://localhost:5432/taxi-service?currentSchema=taxi-service-test

